### ISSUE TITLE
TF implementation of flow ops

### ISSUE THREAD

**Issue by kschmeckpeper** [SudeepDasari/RoboNet#3]
I replaced the custom flow ops with [tf.contrib.image.dense_image_warp](https://www.tensorflow.org/api_docs/python/tf/contrib/image/dense_image_warp) in [this](https://github.com/SudeepDasari/RoboNet/tree/tf_flow_ops) branch.  I ran both versions on a 1080 for 14 hours, using the following configuration.

```
# general experiment configurations
batch_size: 16
train_class: VPredTrainable
max_steps: 300000
train_fraction: 0.1

# list of dictionaries containing data sources along with filter parameters
batch_config:
  # selects sawyer data with autograsp enabled (adim=4, robot=sawyer)
  - data_directory: ${DATA_DIR}/hdf5
    robot: "sawyer"
    adim: 4

# loader_hparams used to initialize loader object
loader_hparams:
  dataset: "RoboNet"
  buffer_size: 10
  load_T: 15
  color_augmentation: 0.1

# model_hparams used to create graph and loss function
model_hparams:
  model: deterministic
  graph_type: c_dna_flow
```

Both versions had close to identical performance.
![image](https://user-images.githubusercontent.com/5781992/62540973-ce3ec900-b826-11e9-8233-f92afdacdd02.png)
The darker line is the custom flow ops, while the lighter line is the tf dense image warp.

However, the custom flow ops seemed to run faster than the tf implementation.
![image](https://user-images.githubusercontent.com/5781992/62541092-0fcf7400-b827-11e9-903a-4f115d31f2c6.png)

@SudeepDasari
